### ISSUE TITLE
handle instructions as markdown

### ISSUE THREAD

**Issue by ashleygwilliams** [ashleygwilliams/js-koans#10]
require-tree only reads .js files, however we want to write them in markdown
- solutions read js file as markdown
- have json object in js file with single key pointing at markdown strings

other options exist, pick one!

**Comment by alicoding** [comment]
As we discussed here we will:

1. Use `instruction.js` to read a markdown file called `README.md` using `fs.readFileSync()` 
2. Then use markdownjs library to transform it to HTML 
3. Send it to the browser from our server.

**Comment by ashleygwilliams** [comment]
solved by #17
